# Generated by Django 5.1.1 on 2024-11-28 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sehatra', '0002_user_is_online'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
