# Generated by Django 5.1.1 on 2024-11-28 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sehatra', '0003_rename_user_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
